---
swagger: '2.0'
info:
  description: Helo Whatsapp API documentation
  version: 1.0.0
  title: 'Helo Whatsapp             '
  termsOfService: ''
  contact:
    name: vivaconnect support
    email: support@vivaconnect.co
host: localhost:3000
basePath: "/helowhatsapp/api"
tags:
- name: message
  description: API's to send bulk messages to end user
- name: users
  description: API's related to login and registration
- name: audience
  description: API's related to whatsapp audience
- name: templates
  description: API's related to whatsapp templates
schemes:
- https
paths:
  "/chat/v1/messages":
    post:
      description: |-
        This API is used to send mesages using a channel.
         This API can send single as well as bulk messsages.
      summary: This API is used to send mesages using a channel
      tags:
      - message
      operationId: send
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: Provided by vivaconnect upon signup
      - name: Body
        in: body
        required: true
        description: Accepts Array of json to send bulk message
        schema:
          example:
          - to: '9112345'
            channels:
            - whatsapp
            whatsapp:
              from: '9167890'
              contentType: location
              location:
                longitude: 7.4954884
                latitude: 51.5005765
          - to: '9112345'
            channels:
            - whatsapp
            whatsapp:
              from: '9167890'
              contentType: template
              template:
                templateId: welcome
                language:
                  policy: deterministic
                  code: en
                components:
                - type: header
                  parameters:
                  - type: text
                    text: Hi!
                  - type: media
                    media:
                      type: document
                      url: http://www.africau.edu/images/default/sample.pdf
                - type: body
                  parameters:
                  - type: text
                    text: Hi!
                  - type: media
                    media:
                      type: document
                      url: http://www.africau.edu/images/default/sample.pdf
                - type: footer
                  parameters:
                  - type: text
                    text: Hi!
                  - type: media
                    media:
                      type: document
                      url: http://www.africau.edu/images/default/sample.pdf
          - to: '9112345'
            channels:
            - whatsapp
            whatsapp:
              from: '9167890'
              contentType: media
              media:
                type: image
                url: https://i.ibb.co/kXgjphY/925869358s.png
                caption: viva connect
          - to: '9112345'
            channels:
            - whatsapp
            whatsapp:
              from: '9167890'
              contentType: text
              text: hello
          type: array
          items:
            "$ref": "#/definitions/sendrequest"
      responses:
        '200':
          description: Returns message ID
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: array
            example:
              code: 2002
              msg: Request Accepted
              data:
              - messageId: 9fcb694e-312f-4945-bc62-008b7a8b376f
                acceptedAt: '2020-07-07T08:33:32.537Z'
              - messageId: 9fcb694e-312f-4945-bc62-008b7a8bjuip
                acceptedAt: '2020-07-07T08:33:32.648Z'
        '400':
          description: Returns invalid request error in error array
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: array
            example:
              code: 4000
              msg: Invalid request
              data: 
              error:
              - invalid body error here
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            type: string
            example: Unauthorized
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/chat/v1/messages/tracking/{messageId}":
    get:
      summary: Get Message Journey
      description: |-
        Use this API to get complete journey of a message
        You need to pass messageId in path
      tags:
      - message
      operationId: getMessageStatus
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: Provided by vivaconnect upon signup
      - name: messageId
        in: path
        required: true
        type: string
        description: Id of a Message
      responses:
        '200':
          description: Returns various stages of message journey
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
            - code: 2000
              msg: Success
              data:
              - messageId: 49bdfe01-0503-487f-8b26-67a2b8fafhjgip
                deliveryChannel: whatsapp
                statusTime: '2020-07-15T13:01:08.000Z'
                state: message forwarded
                endConsumerNumber: '917666545750'
                businessNumber: '91808080808'
              - messageId: 49bdfe01-0503-487f-8b26-67a2b8fafhjgip
                deliveryChannel: whatsapp
                statusTime: '2020-07-15T13:01:00.000Z'
                state: message accepted
                endConsumerNumber: '917666545750'
                businessNumber: '91808080808'
            - code: 3000
              msg: No record found.
              data: 
              error: {}
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/audience/optin":
    post:
      description: "API to update optin\nTo update optinSourceId pass optin source
        ID along with parameters to update\nfollowing are the optin source list :\n1. Captured via any form/check-box/t&c - 154e25f4-44cd-4a48-984d-dbdce569d2c1\n2. When received by direct optin message on Whatsapp - 28614254-12c6-4f44-aa3c-20cf9e9589cb\n3. Optin added using API - 7ccc5ca2-4a8e-4a97-9b49-c5e258bbf649"
      summary: Update optin status and add optin source id
      tags:
      - audience
      operationId: markOptinByPhoneNumberAndAddOptinSource
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/UpdateOptinStatusAndAddOptinSourceIdRequest"
      responses:
        '200':
          description: Returns Status of segment info completion
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
            - code: 2000
              msg: Success
              data:
                optinSourceId: 5ad4bfa0-4dd1-433b-a88b-ace8197f8c38
                optin: true
            - code: 3000
              msg: No record found.
              data: 
              error: {}
        '400':
          description: Returns invalid request error in error array
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: array
            example:
              code: 4000
              msg: Invalid request
              data: 
              error:
              - invalid body error here
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/audience/{audienceId}":
    get:
      summary: Get audience Info
      description: |-
        Use this API to get information of a audience record
        pass audienceId in path
      tags:
      - audience
      operationId: GetAudienceRecordById
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: audienceId
        in: path
        required: true
        type: string
        description: Id of Audience Record
      responses:
        '200':
          description: Returns info of a audience record
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
            - code: 2000
              msg: Success
              data:
                audienceId: ede245a3-9653-41cb-9619-c46ad1d1656c
                phoneNumber: '917666545750'
                channel: whatsapp
                firstMessage: '2020-07-30T11:34:49.000Z'
                lastMessage: '2020-09-10T06:24:18.000Z'
                optin: true
                tempOptin: true
                optinSource: message
                segment_name: 
                chatFlowId: 
                name: Danish
                email: 
                gender: 
                country: 
            - code: 3000
              msg: No record found.
              data: 
              error: {}
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/audience":
    get:
      description: "This api returns list of templates based on filters\nfollowing
        are the list of filters: \nphoneNumber\nfirstMessageActivation\nsegmentId\nchannel\noptinSourceId\noptin\ntempOptin"
      summary: Get audience list
      tags:
      - audience
      operationId: GetAudienceRecordList
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: phoneNumber
        in: query
        required: false
        type: string
        description: ''
      - name: firstMessageActivation
        in: query
        required: false
        type: string
        description: ''
      - name: segmentId
        in: query
        required: false
        type: string
        description: ''
      - name: channel
        in: query
        required: false
        type: string
        description: ''
      - name: optinSourceId
        in: query
        required: false
        type: string
        description: ''
      - name: optin
        in: query
        required: false
        type: boolean
        description: ''
      - name: tempOptin
        in: query
        required: false
        type: boolean
        description: ''
      responses:
        '200':
          description: List of all Templates for audience record
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: array
            example:
            - code: 2000
              msg: Success
              data:
              - audienceId: c1444136-9b15-4bdb-86c3-c138f5a3a44c
                phoneNumber: '919820333891'
                channel: whatsapp
                firstMessage: '2020-07-07T14:48:58.251Z'
                lastMessage: '2020-07-09T13:02:39.018Z'
                optin: true
                tempOptin: true
                optinSource: direct
                segment_name: Organic Conversation
                chatFlowId: 
                name: Ajay
                email: ajay@yopmail.com
                gender: Male
                country: India
              - audienceId: b70aeadd-4941-4bda-a4bd-fd5d320e454f
                phoneNumber: "+91842490276"
                channel: whatsapp
                firstMessage: '2020-07-05T14:06:05.000Z'
                lastMessage: 
                optin: true
                tempOptin: 
                optinSource: direct
                segment_name: Organic Conversation
                chatFlowId: 
                name: Raju
                email: raju@yopmail.com
                gender: Male
                country: India
            - code: 3000
              msg: No record found.
              data: 
              error: {}
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            type: string
            example: Unauthorized
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
    post:
      description: |-
        API to add or update audience
        To add audience do not pass audienceID to update template pass audience ID along with parameters to update
      summary: Add update audience
      tags:
      - audience
      operationId: AddUpdateAudienceData
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/AddupdateAudienceRequest"
      responses:
        '200':
          description: Returns Status of audience info completion
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
            - code: 2000
              msg: Success
              data:
                audienceId: c1444136-9b15-4bdb-86c3-c138f5a3a44c
                phoneNumber: '919820333891'
                channel: whatsapp
                optin: true
                optinSourceId: 5ad4bfa0-4dd1-433b-a88b-ace8197f8c38
                segmentId: a969e894-0317-46ee-95cd-8f56d0b34378
                chatFlowId: 
                name: Ajay
                email: ajay@yopmail.com
                gender: Male
                country: India
            - code: 3000
              msg: No record found.
              data: 
              error: {}
        '400':
          description: Returns invalid request error in error array
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: array
            example:
              code: 4000
              msg: Invalid request
              data: 
              error:
              - invalid body error here
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/templates":
    get:
      description: |-
        This api returns list of templates based on filters
        following are the list of template status :
        Approved
        DELETE_PENDING
        Request Initiated
        SUBMITTED
        Rejected
        REQUESTED
        PENDING
      summary: Get template list
      tags:
      - templates
      operationId: Gettemplatelist
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: messageTemplateStatusId
        in: query
        required: false
        type: string
        description: ''
      responses:
        '200':
          description: List of all Templates for waba account
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: array
            example:
              code: 2000
              msg: Success
              data:
              - messageTemplateId: account_update_1
                TemplateName: account_update_1
                type: Standard Message Template
                categoryName: Account Update
                statusName: Approved
                languageName: English
                mediaType: ''
              - messageTemplateId: account_update_2
                TemplateName: account_update_2
                type: Standard Message Template
                categoryName: Account Update
                statusName: Approved
                languageName: English
                mediaType: ''
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            type: string
            example: Unauthorized
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
    post:
      description: |-
        API to add or update template
        To add template do not pass templateID to update template pass template ID along with parameters to update
      summary: Add update template
      tags:
      - templates
      operationId: Addupdatetemplate
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: user can obtain auth token by using login API
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/AddupdatetemplateRequest"
      responses:
        '200':
          description: Returns Status of template info completion
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
            - code: 2000
              msg: Success
              data:
                mediaTemplateComplete: true
            - code: 3022
              msg: Maximum number of template allowed for this account has exausted.
              data: {}
        '400':
          description: Returns invalid request error in error array
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: array
            example:
              code: 4000
              msg: Invalid request
              data: 
              error:
              - invalid body error here
        '401':
          description: Invalid token in header
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
      security: []
  "/users/authorize":
    post:
      summary: Authorize API
      description: |-
        Authorize API to use API key and generate auth token to be used in other supported API's.
        Token generated using this API have validity of 30 days.
      tags:
      - users
      operationId: authorize
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/authorizeRequest"
      responses:
        '200':
          description: Returns auth token if API key provided is correct
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 2000
              msg: Success
              data:
                apiToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJfaWQiOiIxNTg5ODg2ODA4MTbhgyqojbuegeDWVdjyfdwdjoiZjFkNDQyMDAtNGI5ZC00OTAxLWFlNDktNTAzNWUwYjE0YTVkIiwid2FiYVBob25lTnVtYmVyIjoiOTE4MDgwODAwODA4Iiwic2lnbmF0dXJlIjoiMmQzNjJkMjYtN2NmOS00YmMxLWIxNzItODE5MDA5OWVkYjk0In0sImlhdCI6Mbcdbchdacbacayvcyacyqffdyadfdwfdyfdywfdywfdy.lzyMqKcOlT5UUExEMKeoD_mEfnxOmtCjwv8kCEjl8Uc
        '400':
          description: Returns invalid request error in error array
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: array
            example:
              code: 4000
              msg: Invalid request
              data: 
              error:
              - invalid body error here
        '401':
          description: Invalid token in request
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
            example:
              code: 4001
              msg: Unauthorized access.
              data: 
        '500':
          description: in case of some exceptional error
          headers: {}
          schema:
            properties:
              code:
                type: number
              msg:
                type: string
              data:
                type: object
              error:
                type: object
            example:
              code: 5000
              msg: Something went wrong. Please try again later.
              data: {}
              error: {}
definitions:
  sendrequest:
    title: sendrequest
    example:
      to: '919860245659'
      channels:
      - whatsapp
      isOptin: true
      whatsapp:
        from: '918080800808'
        contentType: template
        template:
          templateId: opt_1
          language:
            policy: deterministic
            code: hi
          components:
          - type: body
            parameters:
            - type: text
              text: VivaConnect
            - type: text
              text: '007'
            - type: text
              text: '2022'
    type: object
    properties:
      to:
        type: string
      channels:
        type: array
        items:
          type: string
      isOptin:
        type: boolean
      whatsapp:
        "$ref": "#/definitions/Whatsapp"
    required:
    - to
    - channels
    - whatsapp
  Whatsapp:
    title: Whatsapp
    example:
      from: '918080800808'
      contentType: template
      template:
        templateId: opt_1
        language:
          policy: deterministic
          code: hi
        components:
        - type: body
          parameters:
          - type: text
            text: VivaConnect
          - type: text
            text: '007'
          - type: text
            text: '2022'
    type: object
    properties:
      from:
        type: string
      contentType:
        type: string
      template:
        "$ref": "#/definitions/Template"
    required:
    - from
    - contentType
    - template
  Template:
    title: Template
    example:
      templateId: opt_1
      language:
        policy: deterministic
        code: hi
      components:
      - type: body
        parameters:
        - type: text
          text: VivaConnect
        - type: text
          text: '007'
        - type: text
          text: '2022'
    type: object
    properties:
      templateId:
        type: string
      language:
        "$ref": "#/definitions/Language"
      components:
        type: array
        items:
          "$ref": "#/definitions/Component"
    required:
    - templateId
    - language
    - components
  Language:
    title: Language
    example:
      policy: deterministic
      code: hi
    type: object
    properties:
      policy:
        type: string
      code:
        type: string
    required:
    - policy
    - code
  Component:
    title: Component
    example:
      type: body
      parameters:
      - type: text
        text: VivaConnect
      - type: text
        text: '007'
      - type: text
        text: '2022'
    type: object
    properties:
      type:
        type: string
      parameters:
        type: array
        items:
          "$ref": "#/definitions/Parameter"
    required:
    - type
    - parameters
  Parameter:
    title: Parameter
    example:
      type: text
      text: VivaConnect
    type: object
    properties:
      type:
        type: string
      text:
        type: string
    required:
    - type
    - text
  updateAccountInfoRequest:
    title: updateAccountInfoRequest
    example:
      firstName: user
      lastName: viva
      city: Mumbai
      state: Maharashtra
      country: IN
      addressLine1: some street
      addressLine2: some lane
      contactNumber: '1234567890'
      phoneCode: "+91"
      postalCode: '400001'
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      city:
        type: string
      state:
        type: string
      country:
        type: string
      addressLine1:
        type: string
      addressLine2:
        type: string
      contactNumber:
        type: string
      phoneCode:
        type: string
      postalCode:
        type: string
  UpdateOptinStatusAndAddOptinSourceIdRequest:
    title: UpdateOptinStatusAndAddOptinSourceIdRequest
    example:
      phoneNumber: '9999999999'
      optinSourceId: 154e25f4-44cd-4a48-984d-dbdce569d2c1
    type: object
    properties:
      phoneNumber:
        type: string
      optinSourceId:
        type: string
    required:
    - optinSourceId
    - phoneNumber
  AddupdateAudienceRequest:
    title: AddupdateaudienceRequest
    example:
    - audienceId: c1444136-9b15-4bdb-86c3-c138f5a3a44c
      phoneNumber: '919820333891'
      channel: whatsapp
      optin: true
      optinSourceId: 5ad4bfa0-4dd1-433b-a88b-ace8197f8c38
      segmentId: a969e894-0317-46ee-95cd-8f56d0b34378
      chatFlowId: 
      name: Ajay
      email: ajay@yopmail.com
      gender: Male
      country: India
    type: array
    items:
      properties:
        audienceId:
          type: string
        phoneNumber:
          type: string
        channel:
          type: string
        optin:
          type: boolean
        optinSourceId:
          type: string
        segmentId:
          type: string
        chatFlowId:
          type: string
        name:
          type: string
        email:
          type: string
        gender:
          type: string
        country:
          type: string
      required:
      - phoneNumber
      - channel
  AddupdatetemplateRequest:
    title: AddupdatetemplateRequest
    example:
      messageTemplateId: 9bf57a21-a05c-47f4-82df-jki09v03deb9
      templateName: Welcome
      type: media message template
      messageTemplateCategoryId: b8203a31-e439-4ea4-a270-bd211317d3ff
      messageTemplateStatusId: c71a8387-80e0-468b-9ee3-abb5ec328176
      messageTemplateLanguageId: 57aa7635-5717-4397-8eb6-4799ef3bec05
      bodyText: Hi {{1}} welcome to our platform
      headerText: ''
      footerText: vivaconnect
      mediaType: image
      secondLanguageRequired: false
      secondMessageTemplateLanguageId: cde192b7-c60f-4d2d-8573-dd5af7c9379b
      secondlanguageBodyText: Hi {{1}} welcome to our platform
      headerType: image
      buttonType: Quick Reply
      buttonData:
        quickReply:
        - '1'
        - '2'
        - '3'
        phoneButtonText: call us
        phoneNumber: '9876543210'
        websiteButtontext: oursite.com
        webAddress: www.google.com
    type: object
    properties:
      messageTemplateId:
        type: string
      templateName:
        type: string
      type:
        type: string
        enum:
        - Standard Message Template
        - Media Message Template
      messageTemplateCategoryId:
        type: string
      messageTemplateStatusId:
        type: string
      messageTemplateLanguageId:
        type: string
      bodyText:
        type: string
      headerText:
        type: string
      footerText:
        type: string
      mediaType:
        type: string
      secondLanguageRequired:
        type: boolean
      secondMessageTemplateLanguageId:
        type: string
      secondlanguageBodyText:
        type: string
      headerType:
        type: string
        enum:
        - Video
        - Pdf
        - Location
        - Text
        - image
      buttonType:
        type: string
        enum:
        - Call To Action
        - Quick Reply
      buttonData:
        "$ref": "#/definitions/ButtonData"
    required:
    - templateName
  ButtonData:
    title: ButtonData
    example:
      quickReply:
      - '1'
      - '2'
      - '3'
      phoneButtonText: call us
      phoneNumber: '9876543210'
      websiteButtontext: oursite
      webAddress: www.google.com
    type: object
    properties:
      quickReply:
        type: array
        items:
          type: string
      phoneButtonText:
        type: string
      phoneNumber:
        type: string
      websiteButtontext:
        type: string
      webAddress:
        type: string
  authorizeRequest:
    title: Authorize Request
    example:
      apiKey: hsdbhsvbsvbs-cbdahcbvdavcd-pojcbnjbc-cshcdvyaya
    type: object
    properties:
      apiKey:
        type: string
    required:
    - apiKey
